### ISSUE TITLE
The itemjoin menu doesnt work

### ISSUE THREAD

**Issue by DreamyzBOTz** [RockinChaos/ItemJoin#373] opened 2021-02-22 17:04 UTC
When you open the itemjoin menu the "modify" tab works but everything else doesnt work
pls fix

**Comment by RockinChaos** [comment] 2021-02-22 22:17
Hi, I need more information to be able to resolve this issue.

On my end, everything is working as intended.

Can you please provide;
1.) Your Spigot version.
2.) Your ItemJoin version found by typing `/itemjoin`
3.) Pastebin.com links of both your config.yml and items.yml.

Once I get those I will work to resolve the issue you are having.

**Comment by RockinChaos** [comment] 2021-06-16 21:18
This bug has been officially fixed in the release of ItemJoin v5.2.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=403809

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes

**Closed by RockinChaos** 2021-06-16 21:18 UTC
Labels: Bug, Fixed - Pending Release
