### ISSUE TITLE
Error on console when using Chestsort 

### ISSUE THREAD

**Issue by kalebbroo** [RockinChaos/ItemJoin#358] opened 2021-01-27 22:43 UTC
**Describe the bug**
If I have items from Itemjoin in my inventory I will get an error on the console. error is in pastebin below.

**To Reproduce**
1. add itemjoin item to chest.
2. open and close chest so chestsort will stack/sort items.
3. see error

**Expected behavior**
chestsort plugin sorts items and does not throw error

**Pastebin**
Error https://pastebin.com/hjsGq7JJ
Items.yml https://pastebin.com/a10DrsUZ
config.yml https://pastebin.com/fb2Db6j0

**Please complete the following information:**
 - Resource Version and Build Number: 5.1.1-SNAPSHOT-b658
 - Server Version Paper 1.16.5

**Comment by mfnalex** [comment] 2021-01-27 22:44
Further info (I am the author of ChestSort and already spoke to the user reporting this):

Used ChestSort version is latest 9.0.1

**Comment by RockinChaos** [comment] 2021-01-27 22:47
> **Describe the bug**
> If I have items from Itemjoin in my inventory I will get an error on the console. error is in pastebin below.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. add itemjoin item to chest.
> 2. open and close chest so chestsort will stack/sort items.
> 3. see error
> 
> **Expected behavior**
> chestsort plugin sorts items and does not throw error
> 
> **Pastebin**
> https://pastebin.com/hjsGq7JJ
> 
> **Please complete the following information:**
> 
> * Resource Version and Build Number: 5.1.1-SNAPSHOT-b658
> * Server Version Paper 1.16.5

Can you please provide your config.yml in a pastebin link.

**Comment by kalebbroo** [comment] 2021-01-27 22:50
Added. I also had it generate a new config with same result.

**Comment by RockinChaos** [comment] 2021-01-27 22:53
> Further info (I am the author of ChestSort and already spoke to the user reporting this):
> 
> Used ChestSort version is latest 9.0.1
> 
> It happens everytime when the ChestSortEvent is called while an ItemJoin item is included in the inventory that is to be sorted. The error comes from a line where the ChestSortAPI isn't used.

Issues seems to be coming from your event.getPlayer() method. Is this supposed to be returning null? If I fetch the inventory holder the player instance `event.getInventory().getViewers().get(0)` returns as a valid player.

**Comment by mfnalex** [comment] 2021-01-27 22:59
ChestSortEvent#getPlayer is @Nullable by design, see here: https://repo.jeff-media.de/javadocs/ChestSortAPI/de/jeff_media/ChestSortAPI/ChestSortEvent.html#getPlayer()

**Comment by mfnalex** [comment] 2021-01-27 23:03
IIRC the getPlayer() only returns a HumanEntity if a PlayerInventory is to be sorted. For normal chests, it always returns null. That might be a bit confusing, I might change that and/or update the API docs, but its clearly stated that getPlayer() may return null

**Comment by RockinChaos** [comment] 2021-01-27 23:06
> ChestSortEvent#getPlayer is @nullable by design, see here: https://repo.jeff-media.de/javadocs/ChestSortAPI/de/jeff_media/ChestSortAPI/ChestSortEvent.html#getPlayer()

Ah okay, yeah it's a bit confusing since it should return a valid player instance any time a chest/inventory is sorted. Since the inventory holder itself returns the player instance.

I guess I will just implement my hacky method for now, for when it returns as null.

**Comment by mfnalex** [comment] 2021-01-27 23:08
> > ChestSortEvent#getPlayer is @nullable by design, see here: https://repo.jeff-media.de/javadocs/ChestSortAPI/de/jeff_media/ChestSortAPI/ChestSortEvent.html#getPlayer()
> 
> Ah okay, yeah it's a bit confusing since it should return a valid player instance any time a chest/inventory is sorted. Since the inventory holder itself returns the player instance.
> 
> I guess I will just implement my hacky method for now, for when it returns as null.

Yeah sorry about that, I can totally understand the confusion. But you also have to keep in mind that its possible for other plugins to invoke the ChestSortEvent, so I can never guarantuee that a player is associated to that Event, that's why it's Nullable.

**Comment by RockinChaos** [comment] 2021-01-27 23:16
> Added. I also had it generate a new config with same result.

Latest snapshot should now fix this issue including your issue #357 .

Link; https://ci.craftationgaming.com/job/ItemJoin/660/
**Remember to remove your old ItemJoin.jar file.**

**Comment by RockinChaos** [comment] 2021-02-16 10:48
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes

**Closed by RockinChaos** 2021-02-16 10:48 UTC
Labels: Bug, Fixed - Pending Release
