### ISSUE TITLE
Got an Error and that dont give items to player

### ISSUE THREAD

**Issue by Stormez1998** [RockinChaos/ItemJoin#431] opened 2021-10-17 09:41 UTC
I get everytime when i join my server an error Message (below). I cant say why. After a while i get a secon message. On my other Servers it works perfect.

ErrorMessage: https://pastebin.com/5i45SgvN
Secon Error Message: https://pastebin.com/MG5SAZti

Itemjoin Version:
 - ItemJoin v5.2.2-RELEASE-b734
Serverversion
 - Magma dce6a22 for Servers in 1.12.2

Thanks for Help

**Comment by RockinChaos** [comment] 2021-10-30 02:40
I apologize for the late reply, I have been experiencing power outages due to a windstorm.

It seems you are using a server fork that isn't supported by ItemJoin. I will see if I can add support for Magma, as there seems to be a conflict with Forge.

**Comment by Stormez1998** [comment] 2021-10-30 11:03
No worries :) Hopefully your fine now :)

That will be very nice bcs Magma is very good, in my oppinion :D

**Comment by RockinChaos** [comment] 2021-11-02 09:51
Okay so! I have an update.

It turns out the issue isn't really with ItemJoin, after trying to fix several "bugs" it turns out the issue is with Magmas implementation of Paper as they have to manually translate everything into Forge language.

I was able to fix a few things to be more compatible but I had to create pull requests on Magmas GitHub to resolve the rest so hopefully they will approve it.

Here is a link to the snapshot;
Link; https://ci.craftationgaming.com/job/ItemJoin/766/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by Stormez1998** [comment] 2021-11-02 14:19
Thanks :) 
I will try it out. Magma has at the Moment also Big Problems with theyre Server. Hopefully they are able to fix that. And i never saw a Coder for a plugin who answer so stabel and is so nice to make a new one :)

**Comment by RockinChaos** [comment] 2021-11-04 23:13
The Magma developers have officially accepted most of my bug fixes, so the next builds of Magma should be more stable.

**Comment by RockinChaos** [comment] 2021-12-16 00:15
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799

**Closed by RockinChaos** 2021-12-16 00:15 UTC
Labels: Bug, Fixed - Pending Release
