### ISSUE TITLE
[Bug] disposable & offhand

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#185] opened 2018-10-23 08:49 UTC
1. When you run command with a disposable item on your "offhand", the item will not be consumed.
- right-click
- multi-click
- inventory

2. Left-click item on your "offhand" will not get anything. 

3. If item has no name, it will casue error.
https://pastebin.com/PfD3m1cY

4. There is one more ' in the item.yml, it will not stop and display lots of error in console until you fixed it.
https://pastebin.com/upLBtuYD

**This is the example item list.**
https://pastebin.com/J7Yz6Cn8

ItemJoin version: 4.9 (build #147 latest)
Spigot Version: git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by momoservertw** [comment] 2018-11-13 08:57
New Example items.
https://pastebin.com/3Qbk0vwN

Testing video.
https://youtu.be/iilmpVqSf_4

**Comment by RockinChaos** [comment] 2018-11-20 19:39
I have tested this build and it seems to be working properly now; http://ci.craftationgaming.com/job/ItemJoin/155/

Let me know if this has resolved your issues and I apologize for the late update. It has been hard to find time this past quarter between college and the new ItemJoin v3 rewrite to be able to respond quickly.

**Comment by momoservertw** [comment] 2018-12-01 17:02
The latest version I tested showed no problem.
Thank you very much.

Besides, I found a little issue.
When you use the custom items on your hand and off-hand at same time, only the command of the item on hand will run.
If the off-hand item is disposable, it will be consumed and not run command when the server get a little lag.

ItemJoin version: 4.9 (build #155 latest)
Spigot Version: git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by momoservertw** [comment] 2018-12-01 17:15
New Example items.
https://pastebin.com/3Qbk0vwN

Testing video.
https://youtu.be/ipkPAWCJFjU

**Comment by RockinChaos** [comment] 2018-12-11 05:18
I apologize for the late reply. It has been hard for me to jump back and forth between the new and old framework since ItemJoin v3 (v5.0.0) is close to exiting development. Each time I jump between frameworks I have to re-learn their systems and structures so I can properly debug it.

So I am a little confused on what the issue is exactly.
1.) When you use the custom items on your hand and off-hand at the same time, only the command of the item on hand will run.

If this is an issue you are referring to this is intended so the main hand runs before the offhand.
(are you wanting both to run?)

2.) If the off-hand item is disposable, it will be consumed and not run command when the server get a little lag.

~~I wasn't ever able to replicate this. Did you double check that it is not a visual glitch by clicking your cursor in the (off-hand) item slot and seeing if it re-appears. Also, re-logging would show if its a visual issue. ~~

EDIT: Finally was able to replicate this. Turns out its not a lag issue. It happens are certain angles of the command execution. If you have both items in your hands (spamming the commands) and at a normal speed drag your cursor from facing directly at your feet to far in front of you (about half-way) you will notice the item disappear. This is definitely not a visual glitch and is a bug.

Issues should be resolved for you in this snapshot; http://ci.craftationgaming.com/job/ItemJoin/157/

**Comment by RockinChaos** [comment] 2018-12-26 19:04
This issue has been officially fixed in the release of ItemJoin v5.0.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254085

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes

**Closed by RockinChaos** 2018-12-26 19:04 UTC
Labels: Bug, Resolved
