### ISSUE TITLE
Player Head Issue

### ISSUE THREAD

**Issue by Nigolaudo** [RockinChaos/ItemJoin#462] opened 2022-02-04 13:09 UTC
**Describe the bug**
I created a Player Head item like Hypixel's Profile Head but after some time the head glitches out and i'm able to move the head in my inventory and the interaction command no longer works. (Note: I have the flag to not move in the inventory)

**To Reproduce**
*Note: Sometimes i just wait and the item glitches.*

1. I click sometimes on the head in my inventory with my cursor
2. I click the Head to open my menu (DeluxeMenus)
3. And it glitches out.

**Expected behavior**
For that the item doesn't bug to be able to function normally as it should.

**Pastebin**
https://pastebin.com/xzcuA7me

**Please complete the following information:**
 - Resource Version and Build Number: [ItemJoin-5.2.4-SNAPSHOT-b799] and [ItemJoin-5.2.3]
 - Server Version [Spigot-1.18]

**Comment by RockinChaos** [comment] 2022-02-05 07:20
Would you be able to provide a screenshot of your `/plugins` output? Just so I can confirm any possible conflicts.

**Comment by Nigolaudo** [comment] 2022-02-07 12:33
https://user-images.githubusercontent.com/89425022/152788699-8b1df581-529b-4854-9a8a-05b7547da943.png

**Comment by Nigolaudo** [comment] 2022-02-12 00:49
@RockinChaos I realized that actually the bug happens whenever I suspend minecraft.

**Comment by Nigolaudo** [comment] 2022-02-12 00:57
Video Showing the Issue (Suspending the Minecraft) https://www.youtube.com/watch?v=FtZE8IVuzNE

**Comment by RockinChaos** [comment] 2022-03-06 08:34
Okay so, after a lot of recoding I have changed how skull items function.
The latest snapshot should resolve your issue; https://ci.craftationgaming.com/job/ItemJoin/802/
**Remember to remove your old ItemJoin.jar file**

Also, to better improve reliability, I recommend using `skull-texture: %player_uuid%` instead as it is more reliable than `%player_name%` since it fetches the texture directly from Mojang.

**Comment by Nigolaudo** [comment] 2022-03-06 13:31
It Worked! Thank you RockinChaos.

**Comment by RockinChaos** [comment] 2022-05-11 10:12
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=451699

**Closed by RockinChaos** 2022-05-11 10:12 UTC
Labels: Bug, Fixed - Pending Release
