### ISSUE TITLE
Error with EntityShootBowEvent

### ISSUE THREAD

**Issue by PlutoCakes** [RockinChaos/ItemJoin#20] opened 2016-03-10 04:28 UTC
For some reason I have only 1 error in my server log and that's
**[Server thread/ERROR]: Could not pass event EntityShootBowEvent to ItemJoin v2.4**

I'm running a 1.8 server and I'm not sure why I have this error?

**Comment by RockinChaos** [comment] 2016-03-10 04:34
Thank you for posting in the report a bug section!
I am aware of this error existing and there is a planned release to fix this. But for the safer side of things can you please post the whole error in pastebin.com and link it? Makes it easier for me to identify what the problem is.

**Comment by PlutoCakes** [comment] 2016-03-10 04:48
Sorry my log is huge so I don't know if this is the correct information.
http://pastebin.com/tDgjZPzB
http://pastebin.com/NasdP0JM

**Comment by RockinChaos** [comment] 2016-03-14 21:42
Ah I see, this is a known bug in ItemJoin 2.4. It has been fixed in version 2.5. Although to be safe you should wait for ItemJoin v2.6 to come out today. I will be uploading it shortly and it shouldn't be long before it is released.

**Closed** 2016-03-14 21:42 UTC
Labels: Bug
