### ISSUE TITLE
Broken GIFImageReader function make plugin can't load

### ISSUE THREAD

**Issue by madokaorimura** [RockinChaos/ItemJoin#226] opened 2019-09-02 02:45 UTC
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource: ItemJoin-v5.0.3
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC: Paper 1.12.2 (1618)
3.) What is the problem that you are having?
GIFImageReader function broken
Image was used: 
![image](https://user-images.githubusercontent.com/24401452/64087700-610c4e00-cd68-11e9-9239-954f84a0943e.gif) *Updated
There was a post about this issue [here](https://stackoverflow.com/questions/22259714/arrayindexoutofboundsexception-4096-while-reading-gif-file)
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
[config.yml](https://gist.github.com/madokaorimura/f4e8f421ca0abc12a080aa3b972fe6aa)
[en-lang.yml](https://gist.github.com/madokaorimura/9d11cece6036190f7de7f129a5b66cec)
[items.yml](https://gist.github.com/madokaorimura/7deacac64f8b1c3e47b6102acc045079)
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.
[Error code](https://pastebin.com/t68y9WuS)

**Comment by RockinChaos** [comment] 2019-09-05 09:22
~ Just a quick status update so it doesn't seem like I am ignoring you.
Looks like this issue might literally be impossible to fix as it is an internal issue with java itself... That's greeeeaaaat... I'll be doing some more research to see if anyone else has found a workaround for such a major bug. Kinda surprised this was allowed to make it to a java release but apparently it is due to lack of the GIFReader being maintained by its developer.

**Comment by RockinChaos** [comment] 2019-09-20 22:01
Okay so I have created a temporary resolution for this issue, the issue is with certain frames with-in the gif itself exceeding an index value of 4096 which causes the internal java dependency for the gif reader to break. It is a known bug that is still not resolved in java itself but I have simply created my own method to catch the error exception and attempt to redraw the frame to fit the bounds.

As of testing with the above gif image and this fix it (looks) to be functioning properly now.
Please see the latest snapshot for the fix; http://ci.craftationgaming.com/job/ItemJoin/

**Comment by RockinChaos** [comment] 2019-09-23 19:01
This bug has been officially fixed in the release of ItemJoin v5.0.4.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=295178

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes

**Closed by RockinChaos** 2019-09-23 19:01 UTC
Labels: Bug, Fixed |Waiting Update|

**Comment by madokaorimura** [comment] 2019-09-24 15:00
Sorry to being inactive
I will check it tomorrow (GMT+7 in here:< )
