### ISSUE TITLE
Item commands.

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#285] opened 2020-05-05 02:35 UTC
**[ Resource Questions / Help and Support ]**
Some problems with the item commands.
I am not sure if I have used these types of commands correctly.
```
multi-click: Execute command when clicked in inventory.
left-click: Execute command when clicked in inventory.
right-click: Execute command when clicked in inventory.

multi-click-air: Never executed
right-click-air: Never executed
left-click-air: Never executed

inventory: No problems.
```
Also, I have some suggestion.
I am using the menu plugin "BossShopPro" which has some great command types.
You can refer to it~ The command type of inventory will be more abundant!
- inventory-left
- inventory-right
- inventory-middle (Mouse wheel)
- inventory-shift-left
- inventory-shift-right
- inventory-shift-middle (BossShop does not have this feature, but maybe you can try it?)

In addition, is it possible to add the "Middle-Click" when players use the mouse wheel.
And it may be clearer to distinguish the Click action from the Inventory action?
***
**Once the following information is provided I will reply to you as quick as possible!**
1. ItemJoin version: v5.0.6   (release)
2. Paper version: Paper version git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) (latest)
3. Test server and default config.yml.
4. item.yml - https://pastebin.com/usZpPZUc
```
# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Custom Item Configurations, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explaination; https://github.com/RockinChaos/ItemJoin/wiki
items-Version: 6
items-Delay: 2
items-Overwrite: false
items-Spamming: false
items-RestrictCount: false
items:
  test:
    id: STONE
    slot: 0
    name: '&bTest Stone'
    commands:
      multi-click:
        - 'message: multi-click'
      right-click:
        - 'message: right-click'
      left-click:
        - 'message: left-click'
      multi-click-air:
        - 'message: multi-click-air'
      right-click-air:
        - 'message: right-click-air'
      left-click-air:
        - 'message: left-click-air'
      inventory:
        - 'message: inventory'
    commands-type: interact, inventory
    itemflags: item-store, placement, death-drops, self-drops
    triggers: disabled
    permission-node: 'itemjoin.item.test'
    enabled-worlds: All
```
5.) Test video: https://youtu.be/57XyBMIIUDI?t=8

Thanks~ : )

**Comment by momoservertw** [comment] 2020-05-05 02:44
By the way, the download link "Download Now" on Spigot has expired.
I downloaded the plugin file from the download History page.

**Comment by RockinChaos** [comment] 2020-05-05 03:36
Hmmm weird, the download link seems to be working for me. What region are you in? I would like to test it with my VPN.

As for the ItemCommands issue, I will be testing this soon. I am currently working on a M.A.S.S.I.V.E commit to the snapshot branch and it pretty much completely rewrites a lot of the pre-exiting methods so I am going to complete it first before I look into further bugs as they might be resolved in this commit. It makes it easier for me to compare v5.0.6 to this future commit.

**Comment by momoservertw** [comment] 2020-05-05 08:53
I am in Taiwan in Asia, if other people can use it, it would not be a big problem~

These issues are not very urgent. Just look at it when you have time. 
I wish you a smooth work and a good day!

**Comment by RockinChaos** [comment] 2020-05-13 07:46
Okay so, the ItemCommands execution you showed above is operating as intended. The "AIR" commands should never be executed in the inventory as those are specific to interaction.

The commands-type options were implemented for simplicity as most people's use-cases were either one or the other, or both. Usually, they were never unique if that makes any sense.

I like your suggestions so what I think I am going to do is remove `commands-type` entirely, changing only the inventory part of things adding the suggested inventory actions and I think I am going to rename the existing `inventory` action to `inventory-all` to simulate both left, right, and middle click.

-- Also the download link seems to work when using a VPN to connect to Taiwan. Though, I think I may stop redirecting to the bukkit site and set the download link to direct download from curse forge so that way it isn't a redirect, of a redirect if that makes any sense haha.

I am going to bump this up to a feature request so I don't get too confused, as I am going to finish up the rest of the bug reports I have to complete before I start implementing new features for the v5.0.7 release.

**Comment by RockinChaos** [comment] 2020-06-24 00:02
Hey, sorry for hijacking your post but I keep getting really confused each time I revisit this issue. I have simply copied your request to your original feature request post #236 manually editing myself it adding it.

If you have any corrections to make please do so in that post. As well as since I referenced the post it will now forever be linked to this issue as well for future reference.

I will be closing this issue as it will now be completed in #236.

**Closed by RockinChaos** 2020-06-24 00:02 UTC
Labels: Feature Request
