### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArrieCodes** [RockinChaos/ItemJoin#55] opened 2016-08-04 14:05 UTC
Hi. When I start my server i get this http://pastebin.com/qJy84Abd

**Comment by RockinChaos** [comment] 2016-08-04 19:28
Thank you for bringing this to my attention. This is a confirmed bug. I have seen this recently when testing the dev builds on my server. I have no idea what is causing it because it is affecting ALL versions of itemjoin with the check for updates option. This error never occurred in the past so it must be something with craftbukkits website. I will continue to further investigate this.

**Comment by RockinChaos** [comment] 2016-08-05 05:46
This has been fixed as of ItemJoin v3.5 and it has been released!

You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107083

**Closed by RockinChaos** 2016-08-05 05:46 UTC
Labels: Bug
