### ISSUE TITLE
Error found in config at:

### ISSUE THREAD

**Issue by Dziaod** [RockinChaos/ItemJoin#281] opened 2020-04-29 20:06 UTC
1.) The version of the Resource.
5.0.6
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
Paper git-Paper-192 (MC: 1.15.2)
3.) What is the problem that you are having?
When I create an Item, and enter the command 'faq' it gives the error: "Error found in config at empty:"
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
https://pastebin.com/UcMJzmwF
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.
In console, it says that the player (I) executed the command.

NOTE: I had to set the world by hand due to the plugin not opening the Worlds Menu

**Comment by RockinChaos** [comment] 2020-04-29 20:46
Can you provide a little more information, please?
I am still not quite understanding what the issue is so maybe a screenshot would be better? I can't tell if this is happening in the ItemJoin menu or when you are trying to execute a command.

Also, steps for replication would be fantastic.

**Comment by Dziaod** [comment] 2020-04-30 05:43
When I use the menu to create a new item, I selected the Knowledge Book first, but any item caused the issue. I selected the slot next, and then the name and lore. Next I set the multi click and inventory commands to ‚faq‘ (Custom Command), and set the region to our spawn region. Due to the server having 120+ worlds, the worlds menu won’t open, so I didn’t click it. I clicked save. I opened the items.yml, added the world line and saved it (It came up with the issue beforehand). I reloaded the plugin and executed /ij get all to get the items, and right clicked the knowledge book, but it still happened and the error still came up. Sometimes it just disappears from the inventory.

**Comment by RockinChaos** [comment] 2020-04-30 06:05
Thanks for the info, I will post back as soon as I figure out what is causing this.

As for the 120+ worlds... I don't even know how you managed to load all of those, you must have 300TB of ram and a magical genie lol. I will look into seeing if I can also resolve the world's menu not opening. Never tested it with so many worlds before.

**Comment by Dziaod** [comment] 2020-04-30 06:17
> Thanks for the info, I will post back as soon as I figure out what is causing this.
> 
> As for the 120+ worlds... I don't even know how you managed to load all of those, you must have 300TB of ram and a magical genie lol. I will look into seeing if I can also resolve the world's menu not opening. Never tested it with so many worlds before.

I can send you a video of the issue, and I will try updating.
To the 120+ worlds, they only get loaded upon enter :)

**Comment by Dziaod** [comment] 2020-04-30 08:33
I found the issue, it was the Knowledge Book, and the error was caused by another plugin. The knowledge book dissapears afte being right-clicked once.

**Comment by RockinChaos** [comment] 2020-04-30 21:23
Okay, so the only bug then is the worlds menu?

**Comment by RockinChaos** [comment] 2020-05-12 08:38
Okay, so I have resolved the issue with the world's menu bug.

All worlds should now be listed in order, if they exceed 36 worlds, they will be pushed to multiple pages that you can click through using the menu buttons.

Snapshot; http://ci.craftationgaming.com/job/ItemJoin/408/

**Comment by RockinChaos** [comment] 2020-08-31 21:20
This bug has been officially fixed in the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes

**Closed by RockinChaos** 2020-08-31 21:20 UTC
Labels: Bug, Fixed - Pending Release
