### ISSUE TITLE
Itemjoin bug v4.5 Spigot 1.8.8

### ISSUE THREAD

**Issue by GoddePlays** [RockinChaos/ItemJoin#211] opened 2019-03-25 19:24 UTC
https://pastebin.com/XeQ1V6nE
-- Console error when i reload

My items.yml --
https://pastebin.com/4gtcM6fX

**Comment by RockinChaos** [comment] 2019-03-25 19:27
Known bug in 4.5, update to the latest version v5.0.3 you are quite a few versions behind.

https://www.spigotmc.org/resources/itemjoin.12661/download?version=262715

Supports MC 1.7-1.12.2

**Comment by GoddePlays** [comment] 2019-03-25 19:27
Wow Thanks, that was quick!

**Comment by GoddePlays** [comment] 2019-03-25 19:28
Will it overide my current items?

**Comment by RockinChaos** [comment] 2019-03-25 19:29
To my knowledge no, it's been quite a while since that version. However your config and enlang files will reset. Any files that do reset will be saved with numbers on the end and you can simply fill out the new fields in the newly generated files.

**Comment by GoddePlays** [comment] 2019-03-25 19:30
ok thanks

**Comment by RockinChaos** [comment] 2019-03-25 23:46
Let me know if something did not work properly, I will close this for now but please re-open this issue if something goes wrong or the issue is not resolved.

**Closed by RockinChaos** 2019-03-25 23:46 UTC
