### ISSUE TITLE
Getting error on "ItemJoin reload" in the newest update.

### ISSUE THREAD

**Issue by Nesseley** [RockinChaos/ItemJoin#151] opened 2018-01-09 08:38 UTC
Version of ItemJoin: 4.6
Spigot: 1.12.2

"ItemJoin Reload" sends an error, **BUT** it also reloads the plugin.
https://pastebin.com/mnbukqv8

**Comment by RockinChaos** [comment] 2018-01-09 17:40
Looks to be an issue with your config file. Can you please send me your items.yml in a pastebin.com?

**Comment by Nesseley** [comment] 2018-01-09 20:17
Yes I was using the console aswell! 
Thanks for fixing it so fast as always! :)

**Comment by SlimeDog** [comment] 2018-01-10 17:22
Spigot 1.12.2 latest
ItemJoin 4.6

Probably fixed per above, but I can confirm NPE on
```
ij reload
```
with an items.yml that hasn't changed for months. No NPE on server start.

**Comment by RockinChaos** [comment] 2018-01-10 17:30
@SlimeDog This has been fixed in the latest snapshot. It has been the only change in that snapshot.

The reason for the bug is it is trying to set %player_location% to console but a console is not a player :P I added a check to make sure it's not null and it fixed it.

**Comment by RockinChaos** [comment] 2018-01-10 20:21
ItemJoin v4.7 has been released and contains this fix; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202738

**Closed by RockinChaos** 2018-01-10 20:21 UTC
Labels: Bug, Fixed |Waiting Update|
