### ISSUE TITLE
Errors with itemjoin 2.7

### ISSUE THREAD

**Issue by BearJW** [RockinChaos/ItemJoin#26] opened 2016-03-29 10:37 UTC
When player changing world , these error will be happened.  

If I use version 2.4 to support 1.8.8 , there are an EntityDamagedByEntityEvent error

[22:14:21] [Server thread/WARN]: [ItemJoin] Task #157 for ItemJoin v2.7 generated an exception java.lang.NullPointerException at me.RockinChaos.itemjoin.Listeners.JoinItem.ChangedWorld.setWorldChangedItems(ChangedWorld.java:38) [?:?] at me.RockinChaos.itemjoin.Listeners.JoinItem.ChangedWorld$1.run(ChangedWorld.java:30) [?:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc] at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by BearJW** [comment] 2016-03-29 13:58
offline server , when some players join , cause this error ,cannot get the head's skin, I am sure that players are online ID

[21:42:53] [Head Conversion Thread - 2/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@130f4b60[id=886d5082-c7c3-4d96-8588-a0e693807db3,name=Defanive,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:70) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:1) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.TileEntitySkull$3.run(TileEntitySkull.java:172) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-f6fba00-9935adc]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by RockinChaos** [comment] 2016-03-29 14:13
I am aware of the first error. Please use the latest version of ItemJoin(v2.7) for backwards support. It will give you a join/respawn/changed world error but it still works. Its just trying to set an offhand slot that does not exist. This has been fixed and will be uploaded with ItemJoin v2.8.

If you could please send your items.yml in a pastebin.com that would be fantastic! By the way for posting error codes pastebin.com is the best way :)

As for the head I have yet to reproduce this issue. I will continue looking into it but my guess is it has something to do with how your server is handling player packets. If this error still occurs when ItemJoin v2.8 is released I will continue looking into this.

**Comment by BearJW** [comment] 2016-03-29 14:30
@RockinChaos  http://pastebin.com/HkQf9NUm

**Comment by RockinChaos** [comment] 2016-03-29 19:41
Everything looks good. Tested it using ItemJoin v2.8-SNAPSHOT and it seems to be working fine in offline mode.

By the way how are the Chinese characters working out? I have never tested ItemJoin in any language other than English. I hope everything is printing smoothly.

**Comment by RockinChaos** [comment] 2016-03-29 20:57
Uploaded ItemJoin v2.8 (bug fixes) please use this and let me know if everything is working!

**Comment by BearJW** [comment] 2016-03-30 04:15
Every Chinese characters if use ANSI encoding on YML files , will work fine on Windows , if use UTF-8 encoding , will work fine on Linux

**Comment by BearJW** [comment] 2016-03-30 04:25
There are no world change error now !  but the head's skin problem is still right there

**Comment by RockinChaos** [comment] 2016-03-30 05:27
Interesting... Do you think you can mess around with your settings a bit? I'm using a fresh spigot & craftbukkit server in offline mode with World Guard, World Edit, ItemJoin, Multiverse-Core & Inventories, PlaceholderAPI and ProtocolLib and I have no problems.

Try this: Install PlaceholderAPI and enable the placeholders for players. Then go to your items.yml and change %player% to %player_name% and see if it works with PlaceholderAPI if it does then something is to be fixed with ItemJoin, if it doesn't then something is wrong with your setup.

Are these players real? Like premium Minecraft accounts. *Purchased*. 

I have never really been this stuck before lol. This puzzles me.

**Comment by BearJW** [comment] 2016-03-30 11:29
That's still not working ..  these players are really really real ,  I used player names like  Notch , Jeb_ , Dinnerbone ......., all of these head's skins were not be loaded , but I installed a skin loading plugin to load player's skin , that worked pretty well

**Comment by BearJW** [comment] 2016-03-30 11:34
my plugin list 
![pl](https://cloud.githubusercontent.com/assets/18140373/14140900/5a89a440-f6ae-11e5-8144-4d4641668684.PNG)

**Comment by RockinChaos** [comment] 2016-03-30 14:21
Interesting... So wait, you tried ItemJoin + PlaceholderAPI  and it still didn't work? Damn.. That puzzles me..

Ill do some digging around and see if I can find anyone with a similar problem & a solution.

**Comment by RockinChaos** [comment] 2016-04-09 23:59
Hey, I have been working on a solution for this and I have a few questions. 

1.) Is this problem still occurring? 
2.) Is this happening to everyone? Or only random people.
3.) Does it work at any time for the player that is not reviving their head (steve/alex skin)?
4.) At this current time what version of CraftBukkit / Spigot are you using?

Thanks! There should be an easy fix to this soon!

**Closed** 2016-04-16 00:04 UTC
Labels: Bug, Resolved
