### ISSUE TITLE
Issue with new skin restorer version

### ISSUE THREAD

**Issue by porudev** [RockinChaos/ItemJoin#520] opened 2023-02-12 06:41 UTC
## Thanks for taking the time to open a bug report!

**Describe the bug**
When i join the server it flood me with errors of unable to give skull object because of the latest SkinRestorer version

**To Reproduce**
1. Server is offline mode
2. Get latest skin restorer
3. Give your self skull item with skull owner's skin
4. Get the error

**Expected behavior**
For the plugin to not spam errors and maybe be compatible

**Screenshots**
![image](https://user-images.githubusercontent.com/81072838/218296999-7f10d72a-29e5-4fef-a1d4-d4bd3a5b59f6.png)

**Pastebin**
It should be detailed enough from the above

**Please complete the following information:**
Paper 1.8.8
Java 11
ItemJoin v5.2.5

**Additional context**
Nope

**Comment by RockinChaos** [comment] 2023-02-12 09:46
Duplicate of #515 please see that issue for the resolution, (the latest snapshot).

**Closed by RockinChaos** 2023-02-12 09:46 UTC
Labels: Bug
