### ISSUE TITLE
Console error Does it have to do with something with my Skull item?

### ISSUE THREAD

**Issue by JimmyEstrada** [RockinChaos/ItemJoin#537] opened 2023-06-21 07:54 UTC
### Server Version

Spigot 1.8.8

### Resource Version

6.0.1-RELEASE-b892

### Dump Information

https://pastebin.com/iZD5WB7b

### Describe The Problem

Hello, I have a problem, this error appears on my console, does it have to do with something from my Skull item? The mistake is this

`21.06 03:49:48 [Server] WARN Exception in thread "Craft Scheduler Thread - 7" 
21.06 03:49:48 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin ItemJoin v6.0.1-RELEASE-b892 generated an exception while executing task 2284
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
21.06 03:49:48 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21.06 03:49:48 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21.06 03:49:48 [Server] INFO at java.lang.Thread.run(Thread.java:750)
21.06 03:49:48 [Server] INFO Caused by: java.lang.IllegalStateException: Asynchronous entity world add!
21.06 03:49:48 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
21.06 03:49:48 [Server] INFO at net.minecraft.server.v1_8_R3.World.b(World.java:2633)
21.06 03:49:48 [Server] INFO at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
21.06 03:49:48 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
21.06 03:49:48 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568)
21.06 03:49:48 [Server] INFO at org.bukkit.Location.getBlock(Location.java:87)
21.06 03:49:48 [Server] INFO at me.RockinChaos.core.utils.api.LegacyAPI.setSkullOwner(LegacyAPI.java:270)
21.06 03:49:48 [Server] INFO at me.RockinChaos.core.handlers.ItemHandler.setStoredSkull(ItemHandler.java:397)
21.06 03:49:48 [Server] INFO at me.RockinChaos.core.handlers.ItemHandler.setSkullOwner(ItemHandler.java:375)
21.06 03:49:48 [Server] INFO at me.RockinChaos.itemjoin.item.ItemMap.setSkull(ItemMap.java:4289)
21.06 03:49:48 [Server] INFO at me.RockinChaos.itemjoin.item.ItemMap.updateItem(ItemMap.java:3883)
21.06 03:49:48 [Server] INFO at me.RockinChaos.itemjoin.item.ItemMap.getItemStack(ItemMap.java:2522)
21.06 03:49:48 [Server] INFO at me.RockinChaos.itemjoin.item.ItemAnimation.lambda$AnimateTask$5(ItemAnimation.java:263)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21.06 03:49:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)`

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment] 2023-07-04 05:03
This does look like its related to your skull item but nothing specifically jumps out at me as incorrect with your configuration so I will need to test this.

I am looking into this now.

**Comment by RockinChaos** [comment] 2023-08-16 02:42
Confirmed, replicated, and fixed in the latest snapshot.
Do note, if `%player_uuid%` results in no-skin texture you will need to use `%player%` instead. Depending on the server, versions below MC 1.11 may experience it simply just not working at all due to API limitations when calling the Mojang website.

So if it works and generates a texture for your skull then you can use it, otherwise swap to `%player%`.

Snapshot link; https://ci.craftationgaming.com/job/ItemJoin/898/
**Remember to remove your old ItemJoin.jar**

**Comment by RockinChaos** [comment] 2023-08-16 09:34
The official release is now available.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=509886
**Remember to remove your old ItemJoin.jar file**

**Closed by RockinChaos** 2023-08-16 09:34 UTC
Labels: Bug, Resolved
