### ISSUE TITLE
Skull head does not word

### ISSUE THREAD

**Issue by MrQuibe** [RockinChaos/ItemJoin#195] opened 2019-01-04 18:51 UTC
1.) ItemJoin v5.0.1
2.) CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-r0.1-SNAPSHOT)
3.) Everytime that I set "%player%" in the "skull-owner" the item stops working. I still receive it, but commands and itemflags still dont working.
4.) https://pastebin.com/0ngfCjFj
  skull:
    id: PLAYER_HEAD
    slot: 3
    name: 'Test'
    skull-owner: '%player%'
    lore:
    - '&7Great for setting a'
    - '&7players profile, like hypixel!'
    commands:
      multi-click:
      - 'message: &cOkay!'
    itemflags: inventory-modify, death-drops, self-drops, item-store, death-drops, self-drops, cancel-events, placement
    triggers: join, respawn, world-change
    enabled-worlds: Spawn

(Nice plugin buddy <3)

**Comment by RockinChaos** [comment] 2019-01-05 20:17
Issue should be resolved in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/182/

Please let me know!

**Comment by MrQuibe** [comment] 2019-01-06 02:45
It's working! Thanks :)
I don't know why, but the dynamic itnes don't refresh.
  gadget:
    id: ENDER_CHEST
    slot: 4
    name: '&aGeneric text'
    lore:
      - '<delay:20>&7Mystery Dust: &b%gadgetsmenu_mystery_dust%'
      - '&7Mystery Box: &b%gadgetsmenu_mystery_boxes%'
    commands:
      multi-click:
      - 'gmenu main'
    commands-type: interact, inventory
    commands-sequence: SEQUENTIAL
    itemflags: dynamic, inventory-modify, death-drops, self-drops, item-store, count-lock, death-drops, self-drops, inventory-modify, cancel-events, placement, item-repairable, item-craftable, hide-attributes
    triggers: join, respawn, world-change
    enabled-worlds: Lobby

I set another placeholders but still don't refreshing.

**Comment by RockinChaos** [comment] 2019-01-06 03:52
My apologies, I have fixed this in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/183/

**Comment by MrQuibe** [comment] 2019-01-06 22:44
The "dynamic" problem remains.

**Comment by RockinChaos** [comment] 2019-01-06 23:57
I apologize, it looks like the spigot API changed with how it handles delays.
I have tested it as working in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/184/

**Comment by MrQuibe** [comment] 2019-01-07 16:45
Still the same bug. Can it be my version of spigot?

**Comment by RockinChaos** [comment] 2019-01-07 22:33
You set up the item incorrectly.

When you add a delay it should look like this; <delay:20>

so it should look like;
lore:
- '<delay:20>&7Mystery Dust: &b%gadgetsmenu_mystery_dust%'


Although that a little weird that it's not working because I copied the exact item you had above except I replaced the placeholder to test the delay properly.

![image](https://user-images.githubusercontent.com/10971577/50797302-2dd0f800-1289-11e9-91b2-3504950b72bb.png)

I am using 1.13.2 (The same version as you) and it is working as intended.
Are you sure you are using the item you provided above?

**Comment by MrQuibe** [comment] 2019-01-07 23:57
I set up a new server to test it but still the same bug. I think it's my spigot

1) https://imgur.com/2MfpAP5
2) https://imgur.com/qaHuHjc
3) https://imgur.com/uCOZFSY
4) https://imgur.com/rHpEPuN

**Comment by RockinChaos** [comment] 2019-01-08 00:31
Okay so I downgraded to the EXACT version (build #) of Spigot 1.13.2 you are using; CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-r0.1-SNAPSHOT)

And it is still working for me.
I also used the images you provided me to produce an exact replica of the situation;
![image](https://user-images.githubusercontent.com/10971577/50801431-8ad4aa00-1299-11e9-94d3-9281a7179947.png)


Here is a video to confirm working;
[img]https://i.imgur.com/SokLPOy.mp4[/img]

I am still not convinced that you are using the fixed ItemJoin snapshot as it doesn't matter what spigot api you are using, I tested it from 1.7-1.13.2 and I can confirm working.

Can you try to delete the ItemJoin far file in your plugins folder and download this latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/186/

**Comment by MrQuibe** [comment] 2019-01-08 00:50
I downloaded the latest snapshot version as I was doing it before and it worked now (Build #186). Sorry about your hard work and thank you for your help.
By the way, sorry for my bad english. Have a nice day :)

**Comment by RockinChaos** [comment] 2019-01-08 00:52
Its all good I am glad I was able to help. If you need any more help feel free to let me know!

**Comment by RockinChaos** [comment] 2019-01-27 05:01
This issue has been officially fixed in the release of ItemJoin v5.0.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=258611

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes

**Closed by RockinChaos** 2019-01-27 05:01 UTC
Labels: Bug, Fixed |Waiting Update|
